# Generated by Django 4.2.23 on 2025-11-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_like_count_post_view_count'),
    ]

    operations = [
    ]
